export const TEXT = {
  en: {
    dashboard: "Dashboard",
    controlCenter: "AquaBiz Control Center",
    heroText: "Sales, AMC, payments, service reminders, and jobs in one place.",
    newBooking: "New Booking",
    amcNewSale: "AMC / New Sale",
    plansProducts: "Plans / Products",
    inventory: "Inventory",
    reports: "Reports",
    businessSettings: "Business Settings",
    customerHistory: "Customer History",
    technicianApp: "Technician App",
    quickActions: "Quick Actions",
    shortcuts: "Important daily shortcuts",
    serviceReminders: "Service Reminders",
    dueOverdue: "Due / overdue customers",
    noReminders: "No reminders due",
    remindersEmpty: "Upcoming service reminders will appear here.",
    recentBookings: "Recent Bookings",
    latestRequests: "Latest customer requests",
    allJobs: "All Jobs",
    noBookings: "No bookings yet",
    newSales: "New Sales",
    amcSales: "AMC Sales",
    monthCollection: "Month Collection",
    bookings: "Bookings",
    reminders: "Reminders",
    lowStock: "Low Stock",
    completedJobs: "Completed Jobs",
    customers: "Customers",
    pending: "Pending",
    view: "View",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    controlCenter: "AquaBiz कंट्रोल सेंटर",
    heroText: "सेल्स, AMC, पेमेंट, सर्विस रिमाइंडर और जॉब्स एक जगह.",
    newBooking: "नई बुकिंग",
    amcNewSale: "AMC / नई बिक्री",
    plansProducts: "प्लान / प्रोडक्ट",
    inventory: "इन्वेंटरी",
    reports: "रिपोर्ट",
    businessSettings: "बिजनेस सेटिंग्स",
    customerHistory: "ग्राहक हिस्ट्री",
    technicianApp: "टेक्नीशियन ऐप",
    quickActions: "क्विक एक्शन",
    shortcuts: "रोजाना इस्तेमाल के जरूरी शॉर्टकट",
    serviceReminders: "सर्विस रिमाइंडर",
    dueOverdue: "ड्यू / ओवरड्यू ग्राहक",
    noReminders: "कोई रिमाइंडर ड्यू नहीं",
    remindersEmpty: "आने वाले सर्विस रिमाइंडर यहां dikhenge.",
    recentBookings: "हाल की बुकिंग",
    latestRequests: "लेटेस्ट ग्राहक रिक्वेस्ट",
    allJobs: "सभी जॉब्स",
    noBookings: "अभी कोई बुकिंग नहीं",
    newSales: "नई बिक्री",
    amcSales: "AMC बिक्री",
    monthCollection: "महीने का कलेक्शन",
    bookings: "बुकिंग",
    reminders: "रिमाइंडर",
    lowStock: "लो स्टॉक",
    completedJobs: "पूरे हुए जॉब्स",
    customers: "ग्राहक",
    pending: "पेंडिंग",
    view: "देखें",
  },
  hinglish: {
    dashboard: "Dashboard",
    controlCenter: "AquaBiz Control Center",
    heroText: "Sales, AMC, payments, service reminders aur jobs ek jagah.",
    newBooking: "New Booking",
    amcNewSale: "AMC / New Sale",
    plansProducts: "Plans / Products",
    inventory: "Inventory",
    reports: "Reports",
    businessSettings: "Business Settings",
    customerHistory: "Customer History",
    technicianApp: "Technician App",
    quickActions: "Quick Actions",
    shortcuts: "Daily use ke important shortcuts",
    serviceReminders: "Service Reminders",
    dueOverdue: "Due / overdue customers",
    noReminders: "No reminders due",
    remindersEmpty: "Upcoming service reminders yahan dikhenge.",
    recentBookings: "Recent Bookings",
    latestRequests: "Latest customer requests",
    allJobs: "All Jobs",
    noBookings: "No bookings yet",
    newSales: "New Sales",
    amcSales: "AMC Sales",
    monthCollection: "Month Collection",
    bookings: "Bookings",
    reminders: "Reminders",
    lowStock: "Low Stock",
    completedJobs: "Completed Jobs",
    customers: "Customers",
    pending: "Pending",
    view: "View",
  },
};

export function getText(language) {
  return TEXT[language] || TEXT.en;
}