export const TEXT = {
  en: {
    dashboard: "Dashboard",
    controlCenter: "AquaBiz Control Center",
    heroText: "Sales, AMC, payments, service reminders, and jobs in one place.",
    newBooking: "New Booking",
    amcNewSale: "AMC / New Sale",
    plansProducts: "Plans / Products",
    inventory: "Inventory",
    reports: "Reports",
    businessSettings: "Business Settings",
    customerHistory: "Customer History",
    technicianApp: "Technician App",
    quickActions: "Quick Actions",
    shortcuts: "Important daily shortcuts",
    serviceReminders: "Service Reminders",
    dueOverdue: "Due / overdue customers",
    noReminders: "No reminders due",
    remindersEmpty: "Upcoming service reminders will appear here.",
    recentBookings: "Recent Bookings",
    latestRequests: "Latest customer requests",
    allJobs: "All Jobs",
    noBookings: "No bookings yet",
    newSales: "New Sales",
    amcSales: "AMC Sales",
    monthCollection: "Month Collection",
    bookings: "Bookings",
    reminders: "Reminders",
    lowStock: "Low Stock",
    completedJobs: "Completed Jobs",
    customers: "Customers",
    pending: "Pending",
    view: "View",
    serviceOverview: "Service Overview",
    serviceOverviewText: "Manage your daily service pipeline and financials.",
    currentMonthCollection: "Current Month Collection",
    lastMonthCollection: "Last Month Collection",
    invoices: "Invoices",
    leads: "Leads",
    jobsPipeline: "Jobs Pipeline",
    collections: "Collections",
    technicianParts: "Technician Parts",
    completedWorkStatus: "Completed work with invoice status.",
    noCompletedJobs: "No completed jobs",
    completedJobsEmpty: "Completed jobs will appear here.",
    createInvoice: "Create Invoice",
    call: "Call",
    login: "Login",
    logout: "Logout",
    mobileNumber: "Mobile number",
    pin6: "6 digit PIN",
    dutyStatus: "Duty Status",
    startDuty: "Start Duty",
    endDuty: "End Duty",
    myJobs: "My Jobs",
    partsWithMe: "Parts With Me",
    hide: "Hide",
    details: "Details",
    currentStatus: "Current Status",
    startJob: "Start Job",
    closeJob: "Close Job",
    stopDuty: "Stop Duty",
    invoiceGenerated: "Invoice Generated",
    generateInvoice: "Generate Invoice",
    invoiceType: "Invoice Type",
    serviceInvoice: "Service Invoice",
    zeroInvoice: "₹0 Invoice",
    amcSale: "AMC Sale",
    newRoSale: "New RO Sale",
    roRental: "RO Rental",
    serviceCharge: "Billing Service Charge",
    actualServiceCharge: "Actual Service Charge",
    paymentCollection: "Payment Collection",
    totalInvoice: "Total Invoice",
    usedParts: "Used Parts",
    addUsedPart: "Add Used Part / Extra Accessory",
    partName: "Part Name",
    category: "Category",
    shopStock: "Shop Stock",
    techStock: "Tech Stock",
    selling: "Selling",
    status: "Status",
    add: "Add",
    remove: "Remove",
    chargePart: "Charge Part",
    waiveCharge: "Waive Charge",
    jobsPipelineSubtitle: "Track all assignments, completions, and repeat jobs in a detailed list.",
    jobTypeFilters: "Job Type / Visit Filters",
    all: "All",
    pendingJobs: "Pending Jobs",
    assigned: "Assigned",
    unassigned: "Unassigned",
    completed: "Completed",
    cancelled: "Cancelled",
    repeat: "Repeat",
    actions: "Actions",
    assign: "Assign",
    edit: "Edit",
    delete: "Delete",
    sendOtp: "Send OTP",
  },
  hi: {
    dashboard: "डैशबोर्ड",
    controlCenter: "AquaBiz कंट्रोल सेंटर",
    heroText: "सेल्स, एएमसी, भुगतान, सर्विस रिमाइंडर और जॉब्स एक ही जगह।",
    newBooking: "नई बुकिंग",
    amcNewSale: "एएमसी / नई बिक्री",
    plansProducts: "प्लान / प्रोडक्ट",
    inventory: "इन्वेंटरी",
    reports: "रिपोर्ट",
    businessSettings: "बिजनेस सेटिंग्स",
    customerHistory: "ग्राहक इतिहास",
    technicianApp: "टेक्नीशियन ऐप",
    quickActions: "त्वरित कार्य",
    shortcuts: "रोजाना इस्तेमाल होने वाले जरूरी शॉर्टकट",
    serviceReminders: "सर्विस रिमाइंडर",
    dueOverdue: "देय / ओवरड्यू ग्राहक",
    noReminders: "कोई रिमाइंडर देय नहीं है",
    remindersEmpty: "आने वाले सर्विस रिमाइंडर यहां दिखाई देंगे।",
    recentBookings: "हाल की बुकिंग",
    latestRequests: "नए ग्राहक अनुरोध",
    allJobs: "सभी जॉब्स",
    noBookings: "अभी कोई बुकिंग नहीं है",
    newSales: "नई बिक्री",
    amcSales: "एएमसी बिक्री",
    monthCollection: "महीने का कलेक्शन",
    bookings: "बुकिंग",
    reminders: "रिमाइंडर",
    lowStock: "कम स्टॉक",
    completedJobs: "पूरे हुए जॉब्स",
    customers: "ग्राहक",
    pending: "बकाया",
    view: "देखें",
    serviceOverview: "सर्विस ओवरव्यू",
    serviceOverviewText: "रोजाना की सर्विस पाइपलाइन और वित्तीय जानकारी संभालें।",
    currentMonthCollection: "इस महीने का कलेक्शन",
    lastMonthCollection: "पिछले महीने का कलेक्शन",
    invoices: "इनवॉइस",
    leads: "लीड्स",
    jobsPipeline: "जॉब पाइपलाइन",
    collections: "कलेक्शन",
    technicianParts: "टेक्नीशियन पार्ट्स",
    completedWorkStatus: "पूरे हुए काम और इनवॉइस की स्थिति।",
    noCompletedJobs: "अभी कोई पूरा हुआ जॉब नहीं है",
    completedJobsEmpty: "पूरे हुए जॉब्स यहां दिखाई देंगे।",
    createInvoice: "इनवॉइस बनाएं",
    call: "कॉल",
    login: "लॉगिन",
    logout: "लॉगआउट",
    mobileNumber: "मोबाइल नंबर",
    pin6: "6 अंकों का पिन",
    dutyStatus: "ड्यूटी स्थिति",
    startDuty: "ड्यूटी शुरू करें",
    endDuty: "ड्यूटी समाप्त करें",
    myJobs: "मेरे जॉब्स",
    partsWithMe: "मेरे पास पार्ट्स",
    hide: "छिपाएं",
    details: "विवरण",
    currentStatus: "वर्तमान स्थिति",
    startJob: "जॉब शुरू करें",
    closeJob: "जॉब बंद करें",
    stopDuty: "ड्यूटी रोकें",
    invoiceGenerated: "इनवॉइस बन चुकी है",
    generateInvoice: "इनवॉइस बनाएं",
    invoiceType: "इनवॉइस प्रकार",
    serviceInvoice: "सर्विस इनवॉइस",
    zeroInvoice: "₹0 इनवॉइस",
    amcSale: "एएमसी बिक्री",
    newRoSale: "नई आरओ बिक्री",
    roRental: "आरओ किराया",
    serviceCharge: "बिलिंग सर्विस चार्ज",
    actualServiceCharge: "वास्तविक सर्विस चार्ज",
    paymentCollection: "भुगतान कलेक्शन",
    totalInvoice: "कुल इनवॉइस",
    usedParts: "इस्तेमाल किए गए पार्ट्स",
    addUsedPart: "इस्तेमाल किया पार्ट / अतिरिक्त सामान जोड़ें",
    partName: "पार्ट का नाम",
    category: "कैटेगरी",
    shopStock: "दुकान स्टॉक",
    techStock: "टेक्नीशियन स्टॉक",
    selling: "बिक्री मूल्य",
    status: "स्थिति",
    add: "जोड़ें",
    remove: "हटाएं",
    chargePart: "पार्ट का चार्ज जोड़ें",
    waiveCharge: "चार्ज हटाएं",
    jobsPipelineSubtitle: "सभी असाइनमेंट, पूरे हुए काम और रिपीट जॉब्स की विस्तृत सूची देखें।",
    jobTypeFilters: "जॉब प्रकार / विजिट फिल्टर",
    all: "सभी",
    pendingJobs: "बकाया जॉब्स",
    assigned: "असाइन",
    unassigned: "अनअसाइन",
    completed: "पूरे हुए",
    cancelled: "रद्द",
    repeat: "रिपीट",
    actions: "कार्य",
    assign: "असाइन",
    edit: "एडिट",
    delete: "डिलीट",
    sendOtp: "OTP भेजें",
  },
  hinglish: {
    dashboard: "Dashboard",
    controlCenter: "AquaBiz Control Center",
    heroText: "Sales, AMC, payments, service reminders aur jobs ek jagah.",
    newBooking: "New Booking",
    amcNewSale: "AMC / New Sale",
    plansProducts: "Plans / Products",
    inventory: "Inventory",
    reports: "Reports",
    businessSettings: "Business Settings",
    customerHistory: "Customer History",
    technicianApp: "Technician App",
    quickActions: "Quick Actions",
    shortcuts: "Daily use ke important shortcuts",
    serviceReminders: "Service Reminders",
    dueOverdue: "Due / overdue customers",
    noReminders: "No reminders due",
    remindersEmpty: "Upcoming service reminders yahan dikhenge.",
    recentBookings: "Recent Bookings",
    latestRequests: "Latest customer requests",
    allJobs: "All Jobs",
    noBookings: "No bookings yet",
    newSales: "New Sales",
    amcSales: "AMC Sales",
    monthCollection: "Month Collection",
    bookings: "Bookings",
    reminders: "Reminders",
    lowStock: "Low Stock",
    completedJobs: "Completed Jobs",
    customers: "Customers",
    pending: "Pending",
    view: "View",
    serviceOverview: "Service Overview",
    serviceOverviewText: "Daily service pipeline aur financials manage karein.",
    currentMonthCollection: "Current Month Collection",
    lastMonthCollection: "Last Month Collection",
    invoices: "Invoices",
    leads: "Leads",
    jobsPipeline: "Jobs Pipeline",
    collections: "Collections",
    technicianParts: "Technician Parts",
    completedWorkStatus: "Completed work ka invoice status.",
    noCompletedJobs: "No completed jobs",
    completedJobsEmpty: "Completed jobs yahan dikhenge.",
    createInvoice: "Create Invoice",
    call: "Call",
    login: "Login",
    logout: "Logout",
    mobileNumber: "Mobile number",
    pin6: "6 digit PIN",
    dutyStatus: "Duty Status",
    startDuty: "Start Duty",
    endDuty: "End Duty",
    myJobs: "My Jobs",
    partsWithMe: "Parts With Me",
    hide: "Hide",
    details: "Details",
    currentStatus: "Current Status",
    startJob: "Start Job",
    closeJob: "Close Job",
    stopDuty: "Stop Duty",
    invoiceGenerated: "Invoice Generated",
    generateInvoice: "Generate Invoice",
    invoiceType: "Invoice Type",
    serviceInvoice: "Service Invoice",
    zeroInvoice: "₹0 Invoice",
    amcSale: "AMC Sale",
    newRoSale: "New RO Sale",
    roRental: "RO Rental",
    serviceCharge: "Billing Service Charge",
    actualServiceCharge: "Actual Service Charge",
    paymentCollection: "Payment Collection",
    totalInvoice: "Total Invoice",
    usedParts: "Used Parts",
    addUsedPart: "Add Used Part / Extra Accessory",
    partName: "Part Name",
    category: "Category",
    shopStock: "Shop Stock",
    techStock: "Tech Stock",
    selling: "Selling",
    status: "Status",
    add: "Add",
    remove: "Remove",
    chargePart: "Charge Part",
    waiveCharge: "Waive Charge",
    jobsPipelineSubtitle: "Assignments, completions aur repeat jobs track karein.",
    jobTypeFilters: "Job Type / Visit Filters",
    all: "All",
    pendingJobs: "Pending Jobs",
    assigned: "Assigned",
    unassigned: "Unassigned",
    completed: "Completed",
    cancelled: "Cancelled",
    repeat: "Repeat",
    actions: "Actions",
    assign: "Assign",
    edit: "Edit",
    delete: "Delete",
    sendOtp: "Send OTP",
  },
};

export function getText(language) {
  return TEXT[language] || TEXT.en;
}
